export default {
    animais: [
        "CORVO", "BALEIA", "BURRO","BALEIA","RAPOSA","ARARA","CANGURU","BALEIA","RAPOSA","COALA","GOLFINHO","DRAGAO","DROMEDARIO","BABUINO","HIPOPOTAMO","ABELHA","ARARA","TUCANO","BESOURO","BAGRE","BOI","BUFALO","BABUINO","CORUJA","COELHO","CAPIVARA","ENGUIA","ESPONJA","ESQUILO","FURAO","FLAMINGO","GAMBA","GIRAFA","GRALHA","GUEPARDO","PAVAO","HIENA","PAVAO"
    ],
    profissoes: [
        "MEDICO","ORTOPEDISTA","ARQUITETO", "TERAPEUTA", "FISICO", "PSICOLOGO", "JORNALISTA", "ANIMADOR", "PROGRAMADOR", "CARTOONISTA", "ATOR", "DIRETOR", "COZINHEIRO", "CANTOR", "PILOTO", "AEROMOÇA", "QUIMICO","MAGICO","ATLETA","VENTRILUCO","MIMICO", "TENISTA","ADVOGADO", "CAMINHONEIRO", "VENDEDOR", "COMERCIANTE", "JOGADOR", "GOLEIRO"
    ],
    generosmusicais: [
        "JAZZ","FUNK","COUNTRY", "ROCK", "BLUES", "SAMBA", "AXE", "PAGODE", "ELETRONICA", "LO-FI", "CLASSICO", "CHILLOUT", "BOSSA-NOVA", "FORRO", "FOLK", "RAP", "GRUNGE", "REGGAE", "HIPHOP", "TRAP", "INSTRUMENTAL", "KPOP", "MPB", "METAL", "POP", "NEW-AGE", "PROGRESSIVO", "SERTANEJO", "SURF", "TROPICAL", "INDIE", "ROCK-CLASSICO", "DEATH-METAL", "DANCE"
    ],
    alimentos: [
        "TORTA","MACARRONADA","LASANHA", "PAO", "CREPE", "SUSHI", "PICOLE", "FRANGO", "GELEIA", "NHOQUE","MUFFIN","COOKIE","SUNDAE","TEMAKI","PEPINO","SALAME","RISOTO","BAGUETE","EMPADA","RAVIOLI","SORVETE","RONDELE","BACALHAU","PANETONE","NACHOS","BOMBOM", "STROGONOFF","FONDUE", "PIPOCA","PASTEL","MACARRAO","MERENGUE","CHOCOLATE","BOLO","BRIGADEIRO","PUDIM","FRANGO"
    ],
    corpohumano: [
        "CRANIO","CORACAO","FIGADO","RIM","COSTELA","VISICULA","RETICULA","OLHO","PANCREAS","FEMUR","LARINGE","FARINGE","PROSTATA","UTERO","BEXIGA","CEREBRO","PELE","TESTICULO","MEDULA","ESPINHA","INTESTINO","ARTERIA","VEIA","PULMAO","TIREOIDE","GLANDULA","CEREBELO","URETRA","BAÇO","TIMO","ROTULA","RADIO"
    ],
    acoesverbos: [
        "CORRER","NADAR","PULAR","DESENHAR","DANCAR","CANTAR","IMITAR","PISCAR","CHEIRAR","OUVIR","LAMBER","COMER","MASTIGAR","JOGAR","APOSTAR"
    ],
    sentimentos: [
        "AMOR","RAIVA","ELFORIA","HOSTILIDADE","TRISTEZA","MEDO","FRUSTRACAO","AVERSAO","ALEGRIA","AFETO","CONFIANCA","CIUME","AMOR","COMPAIXAO","EMPATIA","SURPRESA","ESPERANCA","PAIXAO"
    ],
    hobbies: [
        "MUSICA","PINTURA","CULINARIA","MEDITACAO","TEATRO","CORRIDA","ACADEMIA","YOGA","INSTRUMENTO","DANCA","FOTOGRAFIA","VIAJAR","SURF","PESCA","BARALHO","NATACAO","JOGOSDETABULEIRO","COSTURA","ESCALADA","COLECOES","BICICLETA","PASSEIO","SKATE","ESCRITA","POEMA","PLANTAS","CAMPING","CINEMA","DESENHO","ANIMACAO","PROGRAMACAO","ESCULTURA","PRODUCAOMUSICAL","ARTESANATO","FILME"
    ],
    filmes: [
        "BRANCADENEVE","INTERSTELLAR","TITANIC", "PINOQUIO","MATRIX","CLUBEDALUTA","BUSCAIMPLACAVEL","SENHORDOSANEIS","HARRYPOTTER","EXORCISMO","HOMEMARANHA","VINGADORES","BATMAN","KINGSMAN","EXORCISTA","CINQUENTATONSDECINZA","THEWITCHER","VELOZESEFURIOSOS","MADMAX","RAYA","CARROS","KUNGFUPANDA","VENON"
    ],
    videogames: [
        "RAINFALL","MASS-EFFECT","CRASH", "SUPER-MARIO", "RAIN","THE-LAST-OF-US","RED-DEAD-REDEMPTION","SONIC","BATTLEFIELD","CALL-OF-DUTTY","LEAGUE-OF-LEGENDS","ARMA","UNCHARTED","HORIZON-ZERO-DAWN","UNTIL-DAWN","RESIDENT-EVIL","TONY-HAWK","LITTLE-NIGHTMARES","LIFE-IS-STRANGE","BULLYING","GTA-V","MATRIX","HALO","BLOODBORNE","DARK-SOULS","SEKIRO","SHADOW-OF-THE-COLOSSUS","CYBERPUNK","FORZA", "HITMAN","AGE-OF-EMPIRES","ELDEN-RING","GOD-OF-WAR","THE-WITCHER"
    ]



}